on:
  push:
  # pull_request:

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: "${{ secrets.GHA_TOKEN }}"
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb

      - uses: reitermarkus/automerge@v2
        if: "${{ steps.release.outputs.pr }}"
        with:
          token: ${{ secrets.GHA_TOKEN }}
          # required-labels: automerge
          pull-request: ${{ steps.release.outputs.pr.number }}
