on:
  push:
  pull_request:

jobs:
  release-please:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb
          # command: github-release

      # - run: |
      #     echo PR: "${{ steps.release.outputs.pr }}"

      - uses: reitermarkus/automerge@v2
        if: "${{ steps.release.outputs.pr }}"
        with:
          # token: ${{ secrets.MY_GITHUB_TOKEN }}
          # merge-method: rebase
          # do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ steps.release.outputs.pr.number }}
          # dry-run: true
