on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb
          command: github-release

      - run: |
          echo PR: ${{ steps.release.outputs.pr }}
