name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: "${{ secrets.GHA_TOKEN }}"
          # pull-request-title-pattern: "chore${scope}: release${component} ${version}"
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb
          extra-files: |
            Gemfile.lock

      - uses: actions/github-script@v6
        id: prep-release-pr
        if: ${{ steps.release.outputs.pr }}
        # env:
        #   PR_NUMBER: "${{ toJSON(fromJSON(steps.release.outputs.pr).number) }}"
        with:
          script: |
            const prNumber = "${{ toJSON(fromJSON(steps.release.outputs.pr).number) }}";

            github.rest.issues.addLabels({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["automerge"],
            });

            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE',
            });

      - uses: reitermarkus/automerge@v2
        id: automerge
        if: "${{ steps.release.outputs.pr }}"
        with:
          token: ${{ secrets.GHA_TOKEN }}
          required-labels: automerge
          pull-request: ${{ steps.release.outputs.pr.number }}
