on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: "${{ secrets.GHA_TOKEN }}"
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb

      # - uses: actions/github-script@v6
      #   if: "${{ steps.release.outputs.pr }}"
      #   env:
      #     PR_NUMBER: ${{ toJSON(fromJSON(steps.release.outputs.pr).number) }}
      #   with:
      #     script: |
      #       github.rest.pulls.merge({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: process.env.PR_NUMBER,
      #         merge_method: 'squash'
      #       })

      - uses: actions/github-script@v6
        if: "${{ steps.release.outputs.pr }}"
        env:
          PR_NUMBER: ${{ toJSON(fromJSON(steps.release.outputs.pr).number) }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["automerge"]
            })

      - uses: reitermarkus/automerge@v2
        if: "${{ steps.release.outputs.pr }}"
        with:
          token: ${{ secrets.GHA_TOKEN }}
          required-labels: automerge
          pull-request: ${{ steps.release.outputs.pr.number }}
