on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: "${{ secrets.GHA_TOKEN }}"
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb

      - uses: actions/github-script@v6
        id: prep-release-pr
        if: "${{ steps.release.outputs.pr }}"
        # env:
        #   PR_NUMBER: ${{ toJSON(fromJSON(steps.release.outputs.pr).number) }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ toJSON(fromJSON(steps.release.outputs.pr).number) }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["automerge"],
            })

            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ toJSON(fromJSON(steps.release.outputs.pr).number) }},
              event: 'APPROVE',
            });

      - uses: reitermarkus/automerge@v2
        id: automerge
        if: "${{ steps.release.outputs.pr }}"
        with:
          token: ${{ secrets.GHA_TOKEN }}
          required-labels: automerge
          pull-request: ${{ steps.release.outputs.pr.number }}
