on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: "${{ secrets.GHA_TOKEN }}"
          release-type: ruby
          package-name: foo
          version-file: lib/foo/version.rb

      - if: "${{ steps.release.outputs.pr }}"
        # env:
        #   PR_NUMBER: ${{ steps.release.outputs.pr.number }}
        run: |
          echo "${{ fromJson(steps.release.outputs.pr) }}"
          echo "Number: ${{ fromJson(steps.release.outputs.pr).number }}"
          echo "Number: ${{ fromJson(steps.release.outputs.pr.number) }}"
          echo "Number: ${{ steps.release.outputs.pr.number }}"
          echo "${{ steps.release.outputs.pr }}"

      # - uses: actions/github-script@v6
      #   if: "${{ steps.release.outputs.pr }}"
      #   env:
      #     PR_NUMBER: ${{ steps.release.outputs.pr.number }}
      #   with:
      #     script: |
      #       github.rest.pulls.merge({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: process.env.PR_NUMBER,
      #       })

      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: ["automerge"]
      #       })

      # - uses: reitermarkus/automerge@v2
      #   if: "${{ steps.release.outputs.pr }}"
      #   with:
      #     token: ${{ secrets.GHA_TOKEN }}
      #     required-labels: automerge
      #     pull-request: ${{ steps.release.outputs.pr.number }}
